# Generated by Django 3.2 on 2021-04-25 19:51

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


def add_initial_data(apps, schema_editor):

    TaskStatus = apps.get_model("tasks", "taskstatus")
    draft, _ = TaskStatus.objects.update_or_create(value='draft', defaults={'sorting': 1})
    new, _ = TaskStatus.objects.update_or_create(value='new', defaults={'sorting': 2})

    Task = apps.get_model("tasks", "task")
    Task.objects.update_or_create(name='task 1',fk_status=draft,fsm_status='draft')
    Task.objects.update_or_create(name='task 2', fk_status=new, fsm_status='new')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('value', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sorting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fk_status', models.ForeignKey(default='draft', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tasks.taskstatus')),
                ('fsm_status', django_fsm.FSMKeyField(default='draft', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tasks.taskstatus')),
            ],
        ),
        migrations.RunPython(add_initial_data, reverse_code=migrations.RunPython.noop),
    ]


